apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.name" . }}-deployment
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.labels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "mychart.labels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "mychart.name" . }}-serviceaccount
      {{- end }}
      containers:
        - name: nginx-server
          image: nginx:latest
          ports:
            - name: http-port
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http-port
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: http-port
            periodSeconds: 5
            failureThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html
      volumes:
        - name: index
          configMap:
            name: {{ include "mychart.name" . }}-configmap
