apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.name" . }}-service
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-port
      protocol: TCP
      name: http
  selector:
    {{- include "mychart.labels" . | nindent 4 }}
