{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.name" . }}-serviceaccount
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
{{- end }}
